config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('crud.erp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/erp/urls.py
from django.urls import path
from crud.erp.views.category.views import *
from crud.erp.views.product.views import *

app_name = 'erp'
urlpatterns = [
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

]

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-end">
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a class="font-weight-bold ml-1">Henry González | Cesar Chavarria</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
  <!-- Footer -->
  <footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="text-right text-xl-right text-muted">
          <a class="font-weight-bold ml-1">Henry González</a>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation-fullscreen.html
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
      <div class="container px-4">
        <a class="navbar-brand" href="{% url 'index' %}">
            <h1 class="display-4 text-white">Desarrollo Web</h1>
        </a>
      </div>
    </nav>

templates/includes/navigation.html
{% load static %}

    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block">{{ title }}</a>

        <!-- User -->
        <ul class="navbar-nav align-items-center d-none d-md-flex">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  <img alt="Image placeholder" src="https://fondosmil.com/fondo/2063.jpg" style="height: 40px; width: 40px;">
                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">
                    Developer
                  </span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
              <div class=" dropdown-header noti-title">
                <h6 class="text-overflow m-0">Bienvenido</h6>
              </div>
              <a href="#" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>My profile</span>
              </a>
              <a href="#" class="dropdown-item">
                <i class="ni ni-settings-gear-65"></i>
                <span>Settings</span>
              </a>
              <div class="dropdown-divider"></div>
              <a type="button" class="dropdown-item" data-toggle="modal" data-target="#exampleModal">
                <i class="ni ni-user-run"></i>
                <span>Cerrar Sesión</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <!-- End Navbar -->

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ¿Desea cerrar sesión?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <a  href="" class="btn btn-primary">Si</a>
          </div>
        </div>
      </div>
    </div>

templates/includes/scripts-fullscreen.html
{% load static %}

  <!--   Core   -->
  <script src="{% static 'lib/assets/js/plugins/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'lib/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <!--   Optional JS   -->
  <!--   Argon JS   -->
  <script src="{% static 'lib/assets/js/argon-dashboard.min.js' %}"></script>

templates/includes/scripts.html
{% load static %}

  <script src="https://kit.fontawesome.com/64fbd471c9.js" crossorigin="anonymous"></script>
  <!--   Core   -->
  <script src="{% static 'lib/assets/js/plugins/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
{#  <!--   Optional JS   -->#}
{#  <script src="{% static 'lib/assets/js/plugins/chart.js/dist/Chart.min.js' %}"></script>#}
{#  <script src="{% static 'lib/assets/js/plugins/chart.js/dist/Chart.extension.js' %}"></script>#}
  <!-- Sweetalert2 -->
  <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
  <!--   Argon JS   -->
  <script src="{% static 'lib/assets/js/argon-dashboard.min.js' %}"></script>
  <!--confirm query-->
  <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
  <!-- Funciones -->
  <script src="{% static 'js/functions.js' %}"></script>

templates/includes/sidenav.html
{% load static %}

  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0 text-blue bold" href="#">
        Desarrollo Web Final
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="https://i.pinimg.com/originals/7d/d0/32/7dd032c576c98265b165d281f977fd2d.jpg" style="height: 40px; width: 40px;">
              </span>
            </div>
          </a>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a class="text-danger bold" href="#">
                Desarrollo Web Final
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Navigation -->
        <ul class="navbar-nav">
            {% if 'List' in request.build_absolute_uri %}
                <li class="nav-item active">
                    <a class=" nav-link active " href="{% url 'erp:category_list' %}"> <i class="fas fa-list-alt text-red"></i> Listado
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'erp:category_list' %}"> <i class="fas fa-list-alt text-red"></i> Listado
                    </a>
                </li>
            {% endif %}
            {% if 'category' in request.build_absolute_uri %}
                <li class="nav-item active">
                    <a class=" nav-link active " href="{% url 'erp:category_list' %}"> <i class="fas fa-list-alt text-primary"></i> Categorias
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'erp:category_list' %}"> <i class="fas fa-list-alt text-primary"></i> Categorias
                    </a>
                </li>
            {% endif %}
            {% if 'product' in request.build_absolute_uri %}
                <li class="nav-item active">
                    <a class=" nav-link active " href="{% url 'erp:product_list' %}"> <i class="fas fa-truck-loading text-yellow"></i> Productos
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'erp:product_list' %}"> <i class="fas fa-truck-loading text-yellow"></i> Productos
                    </a>
                </li>
            {% endif %}
        </ul>
        <!-- Heading -->
      </div>
    </div>
  </nav>